version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:${PG_PORT}

  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT_APP}:${PORT_APP}
    env_file:
      - .env
    environment:
      - PG_HOST=${PG_HOST}
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=127.0.0.1"

volumes:
  postgres_volume:
