name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start containers
      run: docker-compose -f "docker-compose-ci.yml" up -d --build

    - name: Run tests
      run: node ace test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose-ci.yml" down
